nameservers:
  - "8.8.8.8"
  - "8.8.4.4"
  - "9.9.9.9"
  - "1.1.1.1"
  - "1.0.0.1"
  - "149.112.112.112"
  - "208.67.222.222"
  - "208.67.220.220"
  - "185.228.168.9"
  - "185.228.169.9"
  - "76.76.19.19"
  - "76.223.122.150"
  - "94.140.14.14"
  - "94.140.15.15"
zones:
  - name: test.net
    ttl: 3600
    records:
      # - name: "@"
      #   type: "A"
      #   ttl: 400
      #   value: "255.255.255.255"

      - name: "@"
        type: "A"
        ttl: 400
        value: "127.0.0.1"

  - name: google.com
    ttl: 3600
    records:
      - name: "@"
        type: "A"
        ttl: 400
        value: "66.254.114.41"

  - name: test2.net
    ttl: 3600
    records:
      - name: "@"
        type: "A"
        ttl: 400
        value: "66.254.114.41"

  - name: yes.com
    ttl: 3600
    records:
      - name: "@"
        type: "A"
        ttl: 400
        value: "127.0.0.1:8003"

    #  TODO:
    # SOA:
    #   mname: ns1.howcode.org
    #   rname: admin.howcode.org
    #   serial: 1111111111
    #   refresh: 3600
    #   retry: 600
    #   expire: 604800
    #   minimum: 86400

    #  TODO:
    # NS:
    #   - host: ns1.test.net
    #   - host: ns2.test.net

    # A:
    #   - name: "@"
    #     type: "A"
    #     ttl: 400
    #     value: "255.255.255.255"

    #   - name: "@"
    #     ttl: 400
    #     value: "127.0.0.1"

    #   - name: "@"
    #     ttl: 400
    #     value: "127.0.0.1"

    #   - name: "@"
    #     ttl: 400
    #     value: "127.0.0.1"

    #   - name: "@"
    #     ttl: 400
    #     value: "10.10.10.10"
